version: '3.6'
services:
  db:
    image: mongo:3.2
    entrypoint: mongod --smallfiles
    volumes:
      - ./data:/data/db
  rocketchat:
    image: rocket.chat:latest
    environment:
      ROOT_URL: 'http://rocketchat.test'
    ports:
      - "8083:3000"
